### ISSUE TITLE
IntelliSense list doesn't go away 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#104]
Windows 8.1 x64

Repro:
1. Start VS and create a powershell script project
2. In the editor type the following code:

```
$ScriptBlock = {
   $ps
```

Once you typed $ps, the intellisense psItem will show up.  Continue typing `$psISE.CurrentFile.`
Notice that the intellisense list doesn't go away.  See the screenshot.
![capture](https://cloud.githubusercontent.com/assets/10081483/6071226/501526e8-ad48-11e4-9d40-85e28c99604f.PNG)

Expected:
The intelliSense list should go away at some point if i don't select from the list.

**Comment by EricJizbaMSFT** [comment]
In addition, the intellisense list doesn't go away after I've finished typing a variable.  For example:

![11](https://cloud.githubusercontent.com/assets/3772771/6084957/9d08bff8-adea-11e4-9f93-2626940407de.png)

Expected:
The intelliSense list goes away after I've completed typing a variable that's in the list (that's what the ISE does)

The pain point is that the Intellisense interrupts my normal typing because I have to type the space bar twice to get one space (once to close Intellisense and once to get a space)

**Comment by ASayre** [comment]
[confirm, still repro]
