### ISSUE TITLE
How do I determine the version/build currently installed?

### ISSUE THREAD

**Issue by gwojan** [microsoft/poshtools#297]
I just installed last night's build and VS Help|About only lists `PowerShell Tools 1.3` instead of `PowerShell Tools for Visual Studio`. This happened with the build two versions ago, I think, on another machine.

Is there a way to view the version of the extension without using Help|About?

**Comment by ASayre** [comment]
Hi @gwojan !

You can view the version by going to Tools- > Extensions and Updates

![image](https://cloud.githubusercontent.com/assets/10080679/6837000/b83b904a-d304-11e4-86be-e9c436b4b273.png)

[I originally was going to point you to $host.Version, but I found a bug there :)]

Does this solve the issue for you?

**Comment by gwojan** [comment]
@AndreSayreMSFT Doh! I've checked the extensions to make sure `poshtools` was installed when it wasn't showing up in Help|About but neglected to check the version. :smirk:

It would be nice though if `poshtools` reported itself in Help|About with the correct version because sometimes I need to export the list for bug reports. The last few builds have been kind of hit or miss but the only version I recall seeing is `1.0`.

**Comment by ASayre** [comment]
No worries!

With regards to the entries in the About dialog, some of the 1.3 versioning that you've seen is due to some internal Visual Studio version numbers leaking out when they don't need to.  They're related to the basic powershell coloring inherent to recent versions of Visual Studio.  I've opened up #302 to address this set of issues.

Closing this issue out, but definitely reopen or create a new issue if there are still issues!
