### ISSUE TITLE
PowerShell Host process broke

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#453]
![image](https://cloud.githubusercontent.com/assets/10080679/7233199/c945b890-e734-11e4-91e7-931a84e25a83.png)

No consistent repro yet, but was just F5'ing [Shift-Alt-F5] ing

**Comment by ASayre** [comment]
Q: Does Shift-Alt-F5 and other Non-F5 entry points follow the same lock?

**Comment by ericdevg** [comment]
Yes, all of the execution should follow same lock. I doubt it was because of lock. Besides how we have host process runs into this state, another thing bothers me is that there does not seem to be an event we can listen for the channel aborted, from where we should be able to recover host process instead of leaving user to this bad state.

**Comment by ASayre** [comment]
Investigate.  Can we detect the failure condition?
