### ISSUE TITLE
Debugging always keep last debugging status and info.

### ISSUE THREAD

**Issue by RongTang** [microsoft/poshtools#548]
![savelastdebuginfo1](https://cloud.githubusercontent.com/assets/12443159/7630985/d630b6b6-fa6e-11e4-9f9e-905ae46a8ae3.png)

VS: dev14 community
OS: windows 8.1 enterprise
Powershell: v4

Repro steps:
    1. Install latest version PoshTools from http://aka.ms/Get-PoshToolsNightly;
    2. Open VS and create a PowerShell project.
    3.Type a sentence with wrong grammar like '& 'C:\$Recycle.Bin' to one method, and then F5, after F5 complete, you can see some error info from the output window;
        4.Delete this wrong sentence '& 'C:\$Recycle.Bin'  from the method in step 3, and then F5 again, verify whether debug will success.

Expect: Debug will success and haven't any error info in output window;
Actual: Debug failed and still have same error info with the last debugging, please see the top screenshot

More Info:
On the contrary, if the last debugging is success, after add some wrong sentences and then the next debugging will success. And when you debug multiple times(>2), debugging will return normal status.

**Comment by ericdevg** [comment]
@RongTang Thanks for reporting issue. Are you sure you are not seeing the original error(which was from last round of run)? I could not repro your issue on my end. Could you double check it by clearing your output window before each debugging run?

**Comment by RongTang** [comment]
Yes, I'm sure. I have verified this issue on another machine, it also repro. And the Output window could only display current debugging info, when you start the next debugging, the last round of debugging info will be automatic cleared. I found the method call locate at ahead of the called method, this issue will repro; In contrast, this issue won't repro.
![callmethod](https://cloud.githubusercontent.com/assets/12443159/7645764/90bbbc74-faec-11e4-923f-6f4ac631a437.png)

**Comment by ericdevg** [comment]
@RongTang I m still not able to get it. Tried on both dev12 and dev14 on 8.1 + PSv4, no repro.
I guess what I originally wanted to say "clearing the Interactive window(a.k.a REPL)", you are right, output window automatically clears for each debugging/execute, however REPL window is keeping all historical log(error).

Would you be able to show me a quick video on onedrive(or some internal places) about that repro, or let's just set up meet so that you can share me your desktop sometime next week?

**Comment by RongTang** [comment]
As my machine has a problem and couldn't make a video, I copy the details steps as below,
VS: Dev14 Community,Dev12 Ult
OS: Win8.1 Ent
PoshTools: V4
1. Install latest version PoshTools from http://aka.ms/Get-PoshToolsNightly;
2. Open VS and create a PowerShell project;
3. Type some codes to editor as pictures right,
   ![untitled0](https://cloud.githubusercontent.com/assets/12443159/7677324/a862db1c-fd7d-11e4-8219-4da094ae88a0.png)
4. F5 and check the Output window as below,
   ![untitled 2png](https://cloud.githubusercontent.com/assets/12443159/7677272/394803ce-fd7d-11e4-8f06-66044f7690db.png)
5. Add this wrong sentence '& 'C:\$Recycle.Bin' to above codes as below,
   ![untitled1](https://cloud.githubusercontent.com/assets/12443159/7677244/fb598434-fd7c-11e4-8071-c39d19e6c7c4.png)

then F5 again and check the Output window as below,
![untitled 2png](https://cloud.githubusercontent.com/assets/12443159/7677272/394803ce-fd7d-11e4-8f06-66044f7690db.png)

More Info:
When you debug multiple times(>2), Output window will show correct info.

Repro machine:
Account: Redmond\vslab2; IP:10.228.109.225
If you're still not repro it, please feel free to tell me, tks.

**Comment by ericdevg** [comment]
@RongTang I think I got what you were seeing there, and probably why. Generally there are a few things need to be clarified;
1. PowerShell script need forward declarations of functions, like header files in C/C++ for example. This can be proved by first time to run your script right after you start new VS instance.
2. The PowerShell runspace is preserved during the entire life of that VS instance.
Within this in mind, 
1. By F5'ing against your script for multiple rounds, you basically call into previous definition of StringContact from last round of run(F5), which explains the weirdness of what you are observing.
2. You should observe the same on powershell ISE.

Thanks for your reporting! I'll close it for now, please reopen it if you see otherwise.
