### ISSUE TITLE
[Remote debugging] There should be some instructions on what should input to Qualifier as it's different from the normal remote debugging

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#659]

**Comment by MrayerMSFT** [comment]
Will be changing to: 

"Allows for debugging of a PowerShell script on a remote machine. Utilizes PowerShell v5.0+ features. This version of PowerShell must be installed on the remote machine in order to remotely debug. Enter the name or address of the machine for which you wish to connect for the qualifier. There is no need to specify transport protocol type (http, tcp, etc.), a port number, or username."

Feel free to make suggestions to the description on this issue as long as it is open.
